import type { MetadataRoute } from 'next'
import { siteUrl } from '@/lib/seo'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/en/',
          '/hu/',
          '/en/services/',
          '/hu/services/',
          '/en/budapest/',
          '/hu/budapest/',
          '/en/pro',
          '/hu/pro',
          '/en/help',
          '/hu/help',
          '/en/terms',
          '/hu/terms',
          '/en/privacy',
          '/hu/privacy',
        ],
        disallow: [
          '/admin/',
          '/en/admin/',
          '/hu/admin/',
          '/messages/',
          '/en/messages/',
          '/hu/messages/',
          '/requests/',
          '/en/requests/',
          '/hu/requests/',
          '/settings/',
          '/en/settings/',
          '/hu/settings/',
          '/appointments/',
          '/en/appointments/',
          '/hu/appointments/',
          '/notifications/',
          '/en/notifications/',
          '/hu/notifications/',
          '/pro/jobs/',
          '/en/pro/jobs/',
          '/hu/pro/jobs/',
          '/pro/messages/',
          '/en/pro/messages/',
          '/hu/pro/messages/',
          '/pro/settings/',
          '/en/pro/settings/',
          '/hu/pro/settings/',
          '/pro/signup/',
          '/en/pro/signup/',
          '/hu/pro/signup/',
          '/login/',
          '/en/login/',
          '/hu/login/',
          '/register/',
          '/en/register/',
          '/hu/register/',
        ],
      },
    ],
    sitemap: `${siteUrl}/sitemap.xml`,
    host: siteUrl,
  }
}
